import type { Metadata } from "next";
import { Header } from "@/components/shared";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next Pizza",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body className="font-nunito" suppressHydrationWarning={true}>
        <main className="min-h-screen">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
