import type { Metadata } from "next";


export const metadata: Metadata = {
    title: "CRAVEMOOD | Dashboard",
    description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body className="font-nunito" suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
