import { Container } from "@/shared/components/shared";
import { Header } from "@/shared/components/shared";
import { Metadata } from "next";


export const metadata: Metadata = {
    title: "CRAVEMOOD | Checkout",
    description: "Generated by create next app",
}

export default function CheckoutLayout({ children }: { children: React.ReactNode }) {
    return (
        <main className="min-h-screen bg-[#F4F1EE]">
            <Container>
                <Header className="border-b-gray-200" hasSearch={false} hasCart={false} />
                {children}
            </Container>
        </main>
    )
}